### ISSUE TITLE
Errors raised when setting `config.raise_on_missing_callback_actions = true`

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train-core#926]
Rails 7.2 introduced a new config option to make it so that an error is raised if the `only` or `except` list in a `before_action` mentions a method that doesn't exist on the controller. Currently the test suite in the starter repo gets a lot of failures if that is enabled.

This test will fail if that config option is set to true:

```
rails test test/controllers/account/scaffolding/completely_concrete/tangible_things_controller_test.rb:28
```

The individual failures look like this and don't include much information:

```
Account::Scaffolding::CompletelyConcrete::TangibleThingsControllerTest
  test_should_get_index                                           FAIL (0.70s)
        Expected response to be a <2XX: success>, but was a <404: Not Found>
        test/controllers/account/scaffolding/completely_concrete/tangible_things_controller_test.rb:30:in `block in <class:TangibleThingsControllerTest>'


Failures and errors:
Account::Scaffolding::CompletelyConcrete::TangibleThingsControllerTest
  test_should_get_index                                           FAIL (0.70s)
        Expected response to be a <2XX: success>, but was a <404: Not Found>
        test/controllers/account/scaffolding/completely_concrete/tangible_things_controller_test.rb:30:in `block in <class:TangibleThingsControllerTest>'
```

If you tail the test log you'll see an error at the bottom of the test run that says this:

```
AbstractController::ActionNotFound (The reorder action could not be found for the #<Proc:0x0000000158051b40 /Users/jgreen/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/cancancan-3.6.1/lib/cancan/controller_resource.rb:15>
callback on Account::Scaffolding::CompletelyConcrete::TangibleThingsController, but it is listed in the controller's
:only option.

Raising for missing callback actions is a new default in Rails 7.1, if you'd
like to turn this off you can delete the option from the environment configurations
or set `config.action_controller.raise_on_missing_callback_actions` to `false`.
):
```

That message points to a file in the `cancancan` gem:

https://github.com/CanCanCommunity/cancancan/blob/c63cde14d419474a9da2ddb03956440045348577/lib/cancan/controller_resource.rb#L15

But that line in `cancancan` is just applying options defined in the controller, so I don't think that `cancancan` is at fault here.

I think this line is what's causing the problem:

https://github.com/bullet-train-co/bullet_train-core/blob/00fdeb275888c88c9a396714c5a7acebbef2e56f/bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb#L88

We're always including the `reorder` action in the list of `collection_actions` even if the model is not sortable. I think we need to either define an empty `reorder` method somewhere that it's available to all super scaffolded controllers, or we need to make it so that `reorder` is only included in the list if the model is actually sortable.

**Comment by jagthedrummer** [comment]
I've been looking into this one and uncovered a few more wrinkles.

My first attempt was to update this block of code:
https://github.com/bullet-train-co/bullet_train-core/blob/00fdeb275888c88c9a396714c5a7acebbef2e56f/bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb#L88

To look like this:

```ruby
collection_actions = (%i[index new create] + collection_actions) - except

if self.method_defined?(:reorder)
  collection_actions << :reorder
end
```

That did seem to fix the original error, but then led to a new one:

```
AbstractController::ActionNotFound (The new action could not be found for the #<Proc:0x000000016983b318 /Users/jgreen/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/cancancan-3.6.1/lib/cancan/controller_resource.rb:15>
callback on Api::V1::Scaffolding::CompletelyConcrete::TangibleThingsController, but it is listed in the controller's
:only option.
```

Now it's complaining about the `new` action not being found. This particular controller is an API controller, so there's actually not a `new` action. So then I updated the block in question to look like this:

```ruby
collection_actions = (%i[index create] + collection_actions) - except

if self.method_defined?(:new)
  collection_actions << :new
end

if self.method_defined?(:reorder)
  collection_actions << :reorder
end
```

That gets that particular test to pass, but it breaks other things. If I go into the app and try to create a new `CreativeConcept` I get this error:

![CleanShot 2024-10-29 at 10 44 08](https://github.com/user-attachments/assets/57e20e3e-ce61-46e6-8e99-fc8d37eae31f)

What's happening is that at the time we call `account_load_and_authorize_resource` the `new` method isn't yet defined on the `CreativeConceptsController`, so `new` isn't added to the `collection_actions` array which means that when we call `prepend_before_action` later in `account_load_and_authorize_resource` we don't have `new` as being an action where those before actions should be called and so we don't end up instantiating the new `@creative_concept` like normal.
